#!/usr/bin/env bash
set -euo pipefail

# 設定（環境変数で上書き可能）
BRANCH="${PATROL_BRANCH:-main}"
SKIP_FORCE_MERGE="${PATROL_SKIP_FORCE_MERGE:-false}"
REPO_URL="https://github.com/nomuvan/harness-harness.git"
MAX_BUDGET="${PATROL_MAX_BUDGET_USD:-5}"
LOG_DIR="/patrol-logs"
LOG_FILE="${LOG_DIR}/patrol-$(date +%Y%m%d-%H%M%S).log"

mkdir -p "$LOG_DIR"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "=== Patrol Start: $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
echo "Branch: $BRANCH | SkipForceMerge: $SKIP_FORCE_MERGE | MaxBudget: \$$MAX_BUDGET"

# 1. ソース取得
if [ -d /workspace/harness-harness ]; then
  cd /workspace/harness-harness
  git fetch origin
  git checkout "$BRANCH"
  git reset --hard "origin/$BRANCH"
else
  git clone -b "$BRANCH" "$REPO_URL" /workspace/harness-harness
  cd /workspace/harness-harness
fi

echo "HEAD: $(git log --oneline -1)"

# 2. Claude CLIで巡回実行
echo "--- Claude CLI patrol start ---"
RESULT=$(claude -p "$(cat /patrol/patrol-prompt.md)" \
  --allowedTools "Bash,Read,Edit,Write,Glob,Grep,WebFetch,WebSearch" \
  --max-budget-usd "$MAX_BUDGET" \
  --output-format json 2>&1) || true

echo "$RESULT" | jq -r '.result // "No result"' 2>/dev/null || echo "$RESULT"
echo "--- Claude CLI patrol end ---"

# 3. 変更チェック
if [ -z "$(git status --porcelain)" ]; then
  echo "No changes detected. Patrol complete."
  echo "=== Patrol End: $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
  exit 0
fi

# 4. PR作成
BRANCH_NAME="patrol/auto-$(date +%Y%m%d)"
git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"
git add -A
git commit -m "patrol: 公式ドキュメント巡回による自動更新 ($(date +%Y-%m-%d))

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"
git push origin "$BRANCH_NAME"

PR_URL=$(gh pr create \
  --title "patrol: 公式ドキュメント自動更新 $(date +%Y-%m-%d)" \
  --body "## Summary

自動巡回により検出された公式ドキュメントの変更を反映。

## 巡回対象
- Claude Code公式ドキュメント
- Codex CLI公式ドキュメント
- 外部プロジェクト（OpenClaw, gstack, superpowers）

🤖 Generated by harness-harness patrol system" \
  --base "$BRANCH" 2>&1)

echo "PR created: $PR_URL"

# 5. マージ判断
if [ "$SKIP_FORCE_MERGE" = "false" ]; then
  echo "Auto-merging PR..."
  sleep 5  # CI起動を少し待つ
  gh pr merge "$PR_URL" --merge --admin 2>&1 || \
    gh pr merge "$PR_URL" --merge 2>&1 || \
    echo "WARN: Auto-merge failed. PR remains open for manual review."
else
  echo "SkipForceMerge=true: PR作成のみ。手動マージ待ち。"
fi

echo "=== Patrol End: $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
